# This workflow creates a Jira task when a new branch is created by Renovate
# It triggers with every new branch created in the repo and skips the build
# unless the branch starts with: "renovate/"

name: Create Jira task

# Controls when the workflow will run
on:
  create:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Checks if the branch starts with: "renovate/"
    if: ${{ startsWith(github.ref, 'refs/heads/renovate/') }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: kceb/pull-request-url-action@v2
        id: pr-url

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: https://searchbroker.atlassian.net
          JIRA_USER_EMAIL: bitbucket@empathy.co
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Jira Create issue
        # You may pin to the exact commit or the version.
        uses: atlassian/gajira-create@v2.0.1
        with:
          # Key of the project
          project: OPS
          # Type of the issue to be created. Example: 'Incident'
          issuetype: Task
          # Issue summary
          summary: |
            [Renovate] ${{ github.repository }} - ${{ github.event.head_commit.message }}
          # Issue description
          description: |
            URL: ${{ steps.pr-url.outputs.url }}
          # fields: '{"customfield_11448": 125}'
