name-template: '$RESOLVED_VERSION' # should be overridden on a project level basis
tag-template: '$RESOLVED_VERSION'
tag-prefix: ''
categories:
  - title: '🔥Breaking Changes'
    labels:
      - 'breaking-change'
  - title: '🎉New Features'
    labels:
      - 'feature'
  - title: '🔝Improvements'
    labels:
      - 'improvement'
      - 'enhancement'
  - title: '🐛Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
  - title: '📦Dependency updates'
    labels:
      - 'dependencies'
  - title: '📚Documentation'
    labels:
      - 'documentation'
  - title: '🧹Deprecations'
    labels:
      - 'deprecation'
  - title: '🔧Maintenance'
    labels:
      - 'chore'
      - 'internal'
      - 'maintenance'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'improvement'
      - 'deprecation'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'dependencies'
      - 'documentation'
      - 'chore'
      - 'internal'
      - 'maintenance'
  default: 'patch'
autolabeler:
  - label: 'breaking-change'
    branch:
      - '/.*!:.*/'
  - label: 'feature'
    branch:
      - '/feature\/.+/i'
      - '/feat\/.+/i'
    title:
      - '/feature.*: /i'
      - '/feat.*: /i'
  - label: 'improvement'
    branch:
      - '/improvement\/.+/i'
    title:
      - '/improvement.*: /i'
  - label: 'bug'
    branch:
      - '/fix\/.+/i'
      - '/bugfix\/.+/i'
      - '/bug\/.+/i'
      - '/hotfix\/.+/i'
    title:
      - '/fix.*: /i'
      - '/bugfix.*: /i'
      - '/bug.*: /i'
      - '/hotfix.*: /i'
  - label: 'dependencies'
    branch:
      - '/dependabot\/.*/'
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - '/docs.*: /i'
  - label: 'deprecation'
    branch:
      - '/deprecation\/.+/i'
    title:
      - '/deprecation.*: .*/i'
  - label: 'helm'
    title:
      - '/Helm/i'
  - label: 'terraform'
    title:
      - '/Terraform/i'
  - label: minor
    body:
      - '/\| minor \|/i'
      - '/\| major \|/i'
replacers:
  - search: '/(\w+)-(\d+)/g'
    replace: '[$1-$2](https://searchbroker.atlassian.net/browse/$1-$2)'

template: "$CHANGES"