template: "## Changes \n $CHANGES"
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 🚀 Features and improvements
    labels:
      - feature
      - enhancement
  - title: 💥 Breaking changes
    labels:
      - breaking-changes
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: 📦 Dependency updates
    labels:
      - dependencies
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: 🔧 Maintenance
    labels:
      - chore
      - internal
      - maintenance
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
      - upgrade
  minor:
    labels:
      - minor
      - enhancement
      - feature
  patch:
    labels:
      - patch
      - bug
      - maintenance
  default: patch
autolabeler:
  - label: 'docs'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/feature/i'
  - label: 'helm'
    title:
      - '/Helm/i'
  - label: 'terraform'
    title:
      - '/Terraform/i'
  - label: minor
    body:
      - '/\| minor \|/i'
      - '/\| major \|/i'
replacers:
  - search: '/(\w+)-(\d+)/g'
    replace: '[$1-$2](${{ secrets.JIRA_BASE_URL }}/browse/$1-$2)'
